controllers/AffiliateProgramController.php
<?php

namespace app\controllers;

use app\models\AccountingReport;
use app\models\AffiliateAccounting;
use app\models\accounting\AffiliateAccountingSearch;
use app\models\Companies;
use app\models\companies\CompaniesSearch;
use app\models\CompanySettings;
use app\models\EmailTemplates;
use app\models\PaymentOrders;
use app\models\PaymentOrdersSearch;
use Yii,
    yii\helpers\Html,
    app\components\helpers\FunctionHelper,
    yii\web\Controller,
    yii\filters\VerbFilter,
    yii\web\Response;
use yii\data\ActiveDataProvider;
use app\models\Users;
use app\models\Settings;

/**
 * BotsController implements the CRUD actions for Bots model.
 */
class AffiliateProgramController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * @return string
     * @throws \Exception
     */
    public function actionIndex()
    {
        $userId = Yii::$app->user->identity->id;
        $referalsProvider = new ActiveDataProvider([
            'query' => Yii::$app->user->identity->type == 1
                ? Users::find()->where(['referal_id' => $userId])
                : Users::find()->where(['not', ['referal_id' => null]])->orderBy(['referal_id' => SORT_DESC]),
        ]);
        $referalsProvider->sort->defaultOrder = ['id' => SORT_DESC];
        
        $retentionProvider = new ActiveDataProvider([
            'query' => Yii::$app->user->identity->type == 1
                ? AffiliateAccounting::find()->where(['company_id' => $userId])->orderBy(['date_transaction' => SORT_DESC])
                : AffiliateAccounting::find()->orderBy(['date_transaction' => SORT_DESC]),
        ]);
        $retentionProvider->sort->defaultOrder = ['id' => SORT_DESC];

        $refPaymentsProvider = new ActiveDataProvider([
            'query' => Yii::$app->user->identity->type == 1
                ? PaymentOrders::find()->where(['company_id' => $userId])->orderBy(['date_order' => SORT_DESC])
                : PaymentOrders::find()->orderBy(['date_order' => SORT_DESC]),
        ]);
        $refPaymentsProvider->sort->defaultOrder = ['id' => SORT_DESC];

        $refPaymentsSearchModel = new PaymentOrdersSearch;
        $setting = Settings::find()->where(['key' => 'partner_programm'])->one();


        /*$companyId = FunctionHelper::getCompanyId();
        $settings = CompanySettings::findOne(['company_id' => $companyId]);
        $company = Companies::findOne($companyId);
        $description = EmailTemplates::findOne(['key' => 'affiliate_program']);
        $retentionSearchModel = new AffiliateAccountingSearch;
        */

        return $this->render('index', [
            'referalsProvider' => $referalsProvider,
            'retentionProvider' => $retentionProvider,
            'refPaymentsProvider' => $refPaymentsProvider,
            'refPaymentsSearchModel' => $refPaymentsSearchModel,
            'description' => $setting->text,
            /*'company' => $company,
            'settings' => $settings,
            'referalsSearchModel' => $referalsSearchModel,
            'retentionSearchModel' => $retentionSearchModel,
            */

        ]);
    }

    /**
     * @return array|string|Response
     */
    public function actionAddOrder()
    {

        $model = new PaymentOrders(['scenario' => PaymentOrders::SCENARIO_SEND_ORDER]);

        $request = Yii::$app->request;
        if (!Yii::$app->user->identity->isSuperAdmin()) {
            $model->company_id = FunctionHelper::getCompanyId();
        }


        if ($request->isPost) {
//            Yii::$app->response->format = Response::FORMAT_JSON;

            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect('index');
                return [
                    'forceReload' => '#crud-datatable-pjax',
                    'title' => "Новая заявка",
                    'size' => 'normal',
                    'content' => '<span class="text-success">Успешно выполнено</span>',
                    'footer' => Html::button('Ок', ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"])
                ];
            }
            return $this->render('accounting/_add-order', ['model' => $model]);
            return [
                'title' => "Новая заявка",
                'size' => 'large',
                'content' => $this->renderAjax('accounting/_add-order', [
                    'model' => $model,
                ]),
                'footer' => Html::button('Отмена', ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                    Html::button('Сохранить', ['class' => 'btn btn-primary', 'type' => "submit"])
            ];
        } else {
            return $this->render('accounting/_add-order', ['model' => $model]);
        }
    }

    public function actionDeleteOrder($id)
    {
        $request = Yii::$app->request;

        $order = $this->findOrder($id);
        if ($order->status != PaymentOrders::STATUS_SUCCESS) {
            $order->delete();
        }


        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];
        } else {
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }

    }

    public function actionExchange()
    {
        $request = Yii::$app->request;

//        Yii::warning($request->isAjax, __METHOD__);

//        if ($request->isPost) {

            Yii::$app->response->format = Response::FORMAT_JSON;

            $order = $this->findOrder($request->get('id'));
            $company = Users::findOne($order->company_id);


            if ($company->partner_balance >= $order->amount) {

                Yii::warning($company->partner_balance);

                $company->partner_balance -= $order->amount;

                $order->status = PaymentOrders::STATUS_SUCCESS;
                $order->date_payment = date('Y-m-d H:i:s');
                $order->save();

                if ($order->type == PaymentOrders::TYPE_BALLANCE) {
                    $company->general_balance += $order->amount;
                    $report = new AccountingReport([
                        'company_id' => $order->company_id,
                        'operation_type' => AccountingReport::TYPE_OUTPUT_AFFILIATE,
                        'amount' => $order->amount,
                        'description' => 'Перевод партнерских отчислений на основной счет',
                    ]);
                    $report->save();
                }
                $company->save();
                $res = ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];
            }
//            $res = ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];
            return  $this->redirect('index');
//        }

    }

    protected function findOrder($id)
    {
        if (($model = PaymentOrders::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

views/affiliate-program/_accounting.php
<?php
use yii\helpers\Html,
    yii\helpers\Url,
    app\components\helpers\FunctionHelper,
    kartik\grid\GridView,
    yii\bootstrap\Modal,
    app\models\Users,
    johnitvn\ajaxcrud\CrudAsset,
    app\models\PaymentOrders;

CrudAsset::register($this);

?>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Мои выплаты</h3>
    </div>
    <div class="panel-body">
        <?= GridView::widget([
            'id' => 'crud-datatable',
            'dataProvider' => $refPaymentsProvider,
            //'filterModel' => $refPaymentsSearchModel,
            'pjax' => true,
            'responsiveWrap' => false,
            'striped' => true,
            'condensed' => true,
            'responsive' => true,
            'toolbar' => [
                ['content' => Yii::$app->user->identity->type == 1
                    ? Html::a('Заказать выплату', ['add-order'], [
//                        'role' => 'modal-remote',
                        'title' => 'Заказать выплату',
                        'class' => 'btn btn-warning btn-sm'
                    ]) : null],
            ],
            'columns' => [

                [
                    'class' => '\kartik\grid\DataColumn',
                    'attribute' => 'company_id',
                    'content' => function ($model) {
                        $company = Users::findOne($model->company_id);
                        return $company->fio;
                    },
                    'visible' => Yii::$app->user->identity->type == 0,
                ],
                [
                    'class' => '\kartik\grid\DataColumn',
                    'attribute' => 'date_order',
                    'content' => function ($model) {
                        return date('H:i d.m.Y', strtotime($model->date_order) );
                    }
                ],
                [
                    'class' => '\kartik\grid\DataColumn',
                    'attribute' => 'date_payment',
                    'content' => function ($model) {
                        return date('H:i d.m.Y', strtotime($model->date_payment) );
                    }
                ],
                [
                    'class' => '\kartik\grid\DataColumn',
                    'attribute' => 'amount',
                    'content' => function ($model) {
                        return number_format($model->amount, 2, ',', ' ') . ' <i class="fa fa-rub"></i>';
                    },
                ],
                [
                    'class' => '\kartik\grid\DataColumn',
                    'attribute' => 'type',
                    'content' => function ($model) {
                        switch ($model->type) {
                            case PaymentOrders::TYPE_CARD;
                                return 'На карту';
                            case PaymentOrders::TYPE_YANDEX;
                                return 'Яндекс Деньги';
                            case PaymentOrders::TYPE_BALLANCE;
                                return 'На балланс';
                            default:
                                return null;
                        }
                    }
                ],
                [
                    'class' => '\kartik\grid\DataColumn',
                    'attribute' => 'requisites',
                    'content' => function ($model) {
                        return $model->requisites;
                    }
                ],
                [
                    'class' => '\kartik\grid\DataColumn',
                    'attribute' => 'status',
                    'content' => function ($model) {
                        switch ($model->status) {
                            case PaymentOrders::STATUS_SUCCESS;
                                return 'Выплачена';
                            default:
                                return 'Заказана';
                        }
                    }
                ],

                [
                    'class' => '\kartik\grid\ActionColumn',
                    'headerOptions' => ['width' => '160'],
                    'template' => '{status}  {delete}',
                    'buttons' => [
                        'status' => function ($url, $model) {
                            $url = Url::to(['/affiliate-program/exchange', 'id' => $model->id]);
                            return (Yii::$app->user->identity->type == 0 && $model->status != PaymentOrders::STATUS_SUCCESS)
                                ? Html::a('<span class="fa fa-check"></span>', $url, [
                                    'class' => 'btn btn-warning btn-sm',
                                    'role' => 'modal-remote',
                                    'title' => 'Перевести',
                                    'data-confirm' => true,
//                                    'data-method' => false,// for overide yii data api
//                                    'data-request-method' => 'post',
                                    'data-toggle' => 'tooltip',
                                    'data-confirm-title' => 'Подтверждение перевода',
                                    'data-confirm-message' => 'Вы увеерены что хотите осуществить этот перевод?',
                                ])
                                : null;
                        },
                        'delete' => function ($url, $model) {
                            $url = Url::to(['delete-order', 'id' => $model->id]);
                            return $model->status != PaymentOrders::STATUS_SUCCESS
                                ? Html::a('<span class="fa fa-trash-o"></span>', $url, [
                                    'class' => 'btn btn-danger btn-sm',
                                    'role' => 'modal-remote',
                                    'title' => 'Перевести',
                                    'data-confirm' => true,
//                                    'data-method' => false,// for overide yii data api
//                                    'data-request-method' => 'post',
                                    'data-toggle' => 'tooltip',
                                    'data-confirm-title' => 'Подтвердите действие',
                                    'data-confirm-message' => 'Вы уверены что хотите удалить эту заявку?',
                                ])
                                : null;
                        },
                    ]
                ]

            ],
            'showPageSummary' => true,
        ]); ?>
    </div>
    <div class="panel-footer"></div>
</div>

<?php Modal::begin([
    "id" => "ajaxCrudModal",
    "footer" => "",// always need it for jquery plugin
]) ?>
<?php Modal::end(); ?>

views/affiliate-program/_description.php
<?php

use yii\helpers\Html;
use app\models\Users;

$affAmount = $company->affiliate_amount ? $company->affiliate_amount : 0;

?>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-6">
                <h3 class="panel-title">Сводные данные</h3>
            </div>
            <div class="col-md-6 text-right" id="refLink">
                <span style="cursor: pointer; color: green" onclick="copyToClipboard('https://fl.teo-job.ru/site/register?ref=<?= Yii::$app->user->identity->id; ?>');"><i class="fa fa-copy"></i> Ваша ссылка:  <span id="copy-to"><?='https://' . $_SERVER['SERVER_NAME'] . '/site/register?ref='. Yii::$app->user->identity->id?></span></span>
            </div>
        </div>
    </div>
    <div class="panel-body" style="padding-bottom: 15px">
        <div class="row">
            <div class="col-md-10 details-affiliate">
                <div class="row">
                    <div class="col-md-1 text-center">
                        <i class="fa fa-credit-card fa-2x"></i>
                    </div>
                    <div class="col-md-4">
                        Баланс партнерского счета
                    </div>
                    <div class="col-md-7 text-bold">
                         <?= number_format(Yii::$app->user->identity->partner_balance, 2, ',', ' ') ?> <i class="fa fa-rub"></i>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-1 text-center">
                        <i class="fa fa-user-secret fa-2x"></i>
                    </div>
                    <div class="col-md-4">
                        Количество рефералов
                    </div>
                    <div class="col-md-7 text-bold">
                        <?= Users::find()->where(['referal_id' => Yii::$app->user->identity->id ])->count() ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-1 text-center">
                        <i class="fa fa-pie-chart fa-2x"></i>
                    </div>
                    <div class="col-md-4">
                        Процентная ставка
                    </div>
                    <div class="col-md-7 text-bold">
                        <?= Yii::$app->user->identity->prosent_referal; ?> %
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-1 text-center">
                        <i class="fa fa-link fa-2x"></i>
                    </div>
                    <div class="col-md-4">
                        Ссылка для привлечения пользователей
                    </div>
                    <div class="col-md-7 text-bold">
                       <?= 'https://' . $_SERVER['SERVER_NAME'] . '/site/register?ref='. Yii::$app->user->identity->id ?> <span style="cursor: pointer; color: green" onclick="copyToClipboard('https://fl.teo-job.ru/site/register?ref=<?= Yii::$app->user->identity->id; ?>');"><i class="fa fa-copy"></i></span>
                        <br/>
                        <div class="copy-result label label-info"></div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-1 text-center">
                    </div>
                    <div class="col-md-4">
                        Количество посещений
                    </div>
                    <div class="col-md-7 text-bold">
                        <?= \app\models\ReferalRedirects::find()->where(['refer_company_id' => Yii::$app->user->identity->id])->count() ?>
                        <br/>
                        <div class="copy-result label label-info"></div>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Принципы и условия работы партнерской программы</h3>
    </div>
    <div class="panel-body" style="padding-bottom: 15px">
        <?=$description?>
    </div>
</div>


<script>
    function copyToClipboard(element) {
        var $temp = $("<input>");
        $("body").append($temp);
        $temp.val(element).select();
        document.execCommand("copy");
        $temp.remove();
        $('.copy-result').html('Скопировано в буфер обмена');
        setTimeout(func, 1000);
    }

    function func() {
        $('.copy-result').empty();
    }

</script>

views/affiliate-program/_referals.php
<?php
use yii\helpers\Html,
    app\components\helpers\FunctionHelper,
    app\models\USers,
    kartik\grid\GridView;

?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Мои рефералы</h3>
    </div>
    <div class="panel-body">
        <?= GridView::widget([
            'id' => 'crud-datatable',
            'dataProvider' => $referalsProvider,
            //'filterModel' => $referalsSearchModel,
            'pjax' => true,
            'responsiveWrap' => false,
            'toolbar' => false,
            'striped' => true,
            'condensed' => true,
            'responsive' => true,
            'columns' => [
                [
                    'class' => '\kartik\grid\DataColumn',
                    'attribute' => 'referal_id',
                    'content' => function ($model) {
                        $referal = Users::findOne($model->referal_id);
                        return $referal->fio;
                    },
                    'visible' => Yii::$app->user->identity->type == 0,
                ],
                [
                    'class' => '\kartik\grid\DataColumn',
                    'attribute' => 'fio',
                    'content' => function ($model) {
                        return $model->fio;
                    }
                ],
                [
                    'class' => '\kartik\grid\DataColumn',
                    'attribute' => 'telephone',
                    'label' => 'Телефон',
                ],
                [
                    'class' => '\kartik\grid\DataColumn',
                    'attribute' => 'register_date',
                    'content' => function ($model) {
                        return $model->register_date == null ? '' : date('H:i d.m.Y', strtotime($model->register_date) );
                    }
                ],

                /*[
                    'class' => '\kartik\grid\DataColumn',
                    'attribute' => 'rate_id',
                    'content' => function ($model) {
                        return $model->rate ? $model->rate->name : null;
                    }
                ],*/

            ],
        ]); ?>
    </div>
    <div class="panel-footer">

    </div>
</div>

views/affiliate-program/_stats.php
<?php
use yii\helpers\Html,
    app\components\helpers\FunctionHelper,
    app\models\USers,
    kartik\grid\GridView;

?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Партнерские отчисления</h3>
    </div>
    <div class="panel-body">
        <?= GridView::widget([
            'id' => 'crud-datatable',
            'dataProvider' => $retentionProvider,
            //'filterModel' => $retentionSearchModel,
            'pjax' => true,
            'responsiveWrap' => false,
            'toolbar' => false,
            'striped' => true,
            'condensed' => true,
            'responsive' => true,
            'columns' => [

                [
                    'class' => '\kartik\grid\DataColumn',
                    'attribute' => 'company_id',
                    'label' => '(Компания) Кому начисляем',
                    'content' => function ($model) {
                        $company = Users::findOne($model->company_id);
                        return $company->fio;
                    },
                    'visible' => Yii::$app->user->identity->type == 0,
                ],

                [
                    'class' => '\kartik\grid\DataColumn',
                    'attribute' => 'referal_id',
                    'label' => 'Реферал',
                    'content' => function ($model) {
                        $referal = Users::findOne($model->company_id);
                        return $referal->fio;
                        //return $model->referalModel ? $model->referalModel->company_name : null;
                    }
                ],
                [
                    'class' => '\kartik\grid\DataColumn',
                    'attribute' => 'date_transaction',
                    'content' => function ($model) {
                        return date('H:i d.m.Y', strtotime($model->date_transaction));
                    }
                ],

                [
                    'class' => '\kartik\grid\DataColumn',
                    'attribute' => 'amount',
                    'content' => function ($model) {
                        return number_format($model->amount, 2, ',', ' ') . ' <i class="fa fa-rub"></i>';
                    },
                    'pageSummary' => function ($summary) {
                        return Html::tag(
                            'div',
                            $summary ? 'Итого: ' .number_format($summary, 2, '.', '') . ' <i class="fa fa-rub"></i>' : null,
                            ['data-sum' => $summary, 'class' => 'text-success']
                        );
                    }
                ],

            ],
            'showPageSummary' => true,
        ]); ?>
    </div>
    <div class="panel-footer"></div>
</div>

views/affiliate-program/index.php
<?php
use Yii,
    yii\helpers\Html,
    yii\helpers\Url,
    yii\bootstrap\Tabs;


$this->title = 'Партнерская программа';

$this->params['breadcrumbs'][] = ['label' => $this->title];

?>

<?php
echo \yii\bootstrap\Tabs::widget([
    'items' => [
        [
            'label' => 'Информация',
            'content' => $this->render('_description', [
                'description' => $description,
                'company' => $company,
                'settings' => $settings,
            ]),
            'active' => true,
        ],
        [
            'label' => 'Рефералы',
            'content' => $this->render('_referals', [
                'referalsProvider' => $referalsProvider,
                'referalsSearchModel' => $referalsSearchModel,
            ]),
        ],
        [
            'label' => 'Статистика',
            'content' => $this->render('_stats', [
                'retentionProvider' => $retentionProvider,
                'retentionSearchModel' => $retentionSearchModel,
            ]),
        ],
        [
            'label' => 'Выплаты',
            'content' => $this->render('_accounting', [
                'refPaymentsProvider' => $refPaymentsProvider,
                'refPaymentsSearchModel' => $refPaymentsSearchModel,
            ]),
        ],
    ]
]);

?>